# Generated by Django 6.0.5 on 2026-06-05 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_firm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaSubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('merchant_request_id', models.CharField(db_index=True, max_length=100)),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100)),
                ('result_code', models.CharField(blank=True, default='', max_length=10)),
                ('result_desc', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='tenants.tenant')),
            ],
        ),
    ]
