# Generated by Django 6.0.5 on 2026-07-04 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_mpesasubscriptionpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('primary_color', models.CharField(default='#0ea5e9', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#0284c7', help_text='Secondary brand color (hex)', max_length=7)),
                ('payslip_header_text', models.CharField(blank=True, default='', max_length=255)),
                ('payslip_footer_text', models.CharField(blank=True, default='', max_length=255)),
                ('working_days', models.JSONField(default=list, help_text='List of working days (0=Monday, 6=Sunday)')),
                ('weekend_days', models.JSONField(default=list, help_text='List of weekend days (0=Monday, 6=Sunday)')),
                ('time_zone', models.CharField(default='Africa/Nairobi', max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('public_holidays', models.JSONField(default=list, help_text='List of public holiday dates (YYYY-MM-DD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
        ),
    ]
