# Generated by Django 6.0.5 on 2026-07-04 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_tenantsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_type', models.CharField(choices=[('leave', 'Leave Request'), ('salary_change', 'Salary Change'), ('employee_onboarding', 'Employee Onboarding'), ('employee_termination', 'Employee Termination'), ('promotion', 'Promotion'), ('transfer', 'Transfer'), ('payroll', 'Payroll'), ('expense', 'Expense Claim'), ('loan', 'Loan Request'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=100)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Order of the step (1, 2, 3...)')),
                ('name', models.CharField(max_length=255)),
                ('approver_type', models.CharField(choices=[('role', 'Specific Role'), ('user', 'Specific User'), ('department_head', 'Department Head')], default='role', max_length=30)),
                ('approver_role', models.CharField(blank=True, default='', help_text="Role required if approver_type is 'role'", max_length=50)),
                ('requires_comment', models.BooleanField(default=False, help_text='Whether approval requires a comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver_user', models.ForeignKey(blank=True, help_text="Specific user if approver_type is 'user'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('delegate', 'Delegate')], max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approval_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.approvalrequest')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='workflows.approvalstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('workflow_type', models.CharField(choices=[('leave', 'Leave Request'), ('salary_change', 'Salary Change'), ('employee_onboarding', 'Employee Onboarding'), ('employee_termination', 'Employee Termination'), ('promotion', 'Promotion'), ('transfer', 'Transfer'), ('payroll', 'Payroll'), ('expense', 'Expense Claim'), ('loan', 'Loan Request'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_templates', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.approvaltemplate'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='workflows.approvaltemplate'),
        ),
        migrations.AddIndex(
            model_name='approvaltemplate',
            index=models.Index(fields=['tenant', 'workflow_type'], name='workflows_a_tenant__857e93_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_template_step_order'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['tenant', 'status'], name='workflows_a_tenant__2db004_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['tenant', 'requester'], name='workflows_a_tenant__c8e6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['tenant', 'workflow_type'], name='workflows_a_tenant__9dc541_idx'),
        ),
    ]
