# Generated by Django 6.0.5 on 2026-05-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_emp_tenant_status_idx_and_more'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'status'], name='leave_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'start_date'], name='leave_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_date_range_idx'),
        ),
    ]
