# Generated by Django 6.0.5 on 2026-06-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_leave_employee_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
