# Generated by Django 6.0.5 on 2026-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_latitude_attendance_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_public_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_sunday',
            field=models.BooleanField(default=False),
        ),
    ]
