# Generated by Django 6.0.5 on 2026-05-13 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nssf_rate', models.DecimalField(decimal_places=4, default=0.06, max_digits=5)),
                ('nssf_cap', models.DecimalField(decimal_places=2, default=4320.0, max_digits=10)),
                ('shif_rate', models.DecimalField(decimal_places=4, default=0.0275, max_digits=5)),
                ('shif_min', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('ahl_rate', models.DecimalField(decimal_places=4, default=0.015, max_digits=5)),
                ('personal_relief', models.DecimalField(decimal_places=2, default=2400.0, max_digits=10)),
                ('paye_bands', models.JSONField(default=list)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('nssf', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shif', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ahl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollrun')),
            ],
        ),
    ]
