# Generated by Django 6.0.5 on 2026-05-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_emp_tenant_status_idx_and_more'),
        ('payroll', '0001_initial'),
        ('tenants', '0003_firm_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['payroll_run', 'employee'], name='pi_run_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['tenant', 'status'], name='pr_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['tenant', 'year', 'month'], name='pr_tenant_period_idx'),
        ),
    ]
