# Generated by Django 6.0.5 on 2026-06-01 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_bank_details_alter_employee_kra_pin_and_more'),
        ('payroll', '0002_payrollitem_pi_run_employee_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('conversation_id', models.CharField(blank=True, default='', max_length=100)),
                ('originator_conversation_id', models.CharField(blank=True, default='', max_length=100)),
                ('result_code', models.CharField(blank=True, default='', max_length=10)),
                ('result_desc', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='employees.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='payroll.payrollrun')),
            ],
            options={
                'indexes': [models.Index(fields=['payroll_run', 'status'], name='mpesa_run_status_idx'), models.Index(fields=['conversation_id'], name='mpesa_conv_id_idx')],
            },
        ),
    ]
