# Generated by Django 6.0.5 on 2026-06-22 09:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollitem_payslip_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollconfig',
            name='nssf_act',
            field=models.CharField(choices=[('new', 'New NSSF Act 2013 (Tier I + Tier II)'), ('old', 'Old NSSF Act (Flat KES 200)')], default='new', max_length=5),
        ),
        migrations.AddField(
            model_name='payrollconfig',
            name='nssf_lel',
            field=models.DecimalField(decimal_places=2, default=Decimal('7000.00'), help_text='NSSF Lower Earnings Limit (Tier I ceiling)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollconfig',
            name='nssf_uel',
            field=models.DecimalField(decimal_places=2, default=Decimal('36000.00'), help_text='NSSF Upper Earnings Limit (Tier II ceiling)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reversed_by',
            field=models.OneToOneField(blank=True, help_text='Points to the corrective run that reversed this run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='payroll.payrollrun'),
        ),
        migrations.AlterField(
            model_name='payrollconfig',
            name='ahl_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0150'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollconfig',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(blank=True, help_text='Geofence radius in metres around the office. Leave blank to disable.', null=True),
        ),
        migrations.AlterField(
            model_name='payrollconfig',
            name='nssf_cap',
            field=models.DecimalField(decimal_places=2, default=Decimal('4320.00'), help_text='Legacy cap field (kept for reference; engine uses lel/uel)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollconfig',
            name='nssf_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0600'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollconfig',
            name='paye_bands',
            field=models.JSONField(default=list, help_text='[{"limit": 24000, "rate": 0.10}, ...] — empty = KRA 2024/2025 defaults'),
        ),
        migrations.AlterField(
            model_name='payrollconfig',
            name='shif_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('300.00'), help_text='Minimum SHIF deduction per month (KES 300)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollconfig',
            name='shif_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0275'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('approved', 'Approved'), ('paid', 'Paid'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
    ]
