# Generated by Django 6.0.5 on 2026-06-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollconfig_nssf_act_payrollconfig_nssf_lel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20),
        ),
    ]
