# Generated by Django 6.0.5 on 2026-06-01 01:15

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_emp_tenant_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_details',
            field=core.encryption.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=core.encryption.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mpesa_number',
            field=core.encryption.EncryptedCharField(blank=True, null=True),
        ),
    ]
