# Generated by Django 6.0.5 on 2026-06-22 09:28

import core.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_bank_details_alter_employee_kra_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='county',
            field=models.CharField(blank=True, default='', help_text='County of residence / work station', max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=core.encryption.EncryptedCharField(blank=True, default='', help_text='National ID / Alien ID / Passport number (encrypted)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, default='Kenyan', help_text='Affects PAYE treatment (expats may have different rules)', max_length=60),
        ),
        migrations.AddField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(blank=True, default='', help_text='NSSF membership number — required for remittance schedule', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='payroll_number',
            field=models.CharField(blank=True, default='', help_text='Internal payroll/employee number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='shif_number',
            field=models.CharField(blank=True, default='', help_text='SHIF/NHIF membership number — required for SHIF schedule', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_number',
            field=models.CharField(blank=True, default='', help_text='Required for non-citizen employees', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=core.encryption.EncryptedCharField(blank=True, default='', help_text='KRA Personal Identification Number'),
        ),
    ]
