# Generated by Django 6.0.5 on 2026-07-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_county_employee_national_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of birth — used for birthday reminders', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='confirmed_date',
            field=models.DateField(blank=True, help_text='Date employee was confirmed after probation', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Fixed-term contract end date — triggers expiry alerts', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, help_text='Date employee left the organisation', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='lifecycle_stage',
            field=models.CharField(choices=[('hired', 'Hired'), ('onboarding', 'Onboarding'), ('probation', 'On Probation'), ('confirmed', 'Confirmed'), ('transferred', 'Transferred'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('retired', 'Retired'), ('archived', 'Archived')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, help_text='End of probation — triggers automated alert 7 days before', null=True),
        ),
    ]
