# Generated by Django 6.0.5 on 2026-06-01 02:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

# ── PostgreSQL tamper-lock trigger ────────────────────────────────────────────
# Fires BEFORE any UPDATE or DELETE on core_auditlog — raises an exception
# unconditionally.  Even a direct psql session or DB admin cannot silently
# modify/remove a row without first DROPping the trigger (a traceable DDL op).
_CREATE_IMMUTABILITY_TRIGGER = """
CREATE OR REPLACE FUNCTION core_auditlog_immutability_guard()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION
        'Security violation: AuditLog records are immutable. '
        'Operation: %%, Row ID: %%. '
        'This incident has been logged.',
        TG_OP, OLD.id;
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_auditlog_immutability
BEFORE UPDATE OR DELETE
ON core_auditlog
FOR EACH ROW
EXECUTE FUNCTION core_auditlog_immutability_guard();
"""

_DROP_IMMUTABILITY_TRIGGER = """
DROP TRIGGER IF EXISTS trg_auditlog_immutability ON core_auditlog;
DROP FUNCTION IF EXISTS core_auditlog_immutability_guard();
"""


def create_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(_CREATE_IMMUTABILITY_TRIGGER)

def drop_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(_DROP_IMMUTABILITY_TRIGGER)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_firm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.CharField(db_index=True, max_length=255)),
                ('actor_email', models.EmailField(blank=True, max_length=255)),
                ('action', models.CharField(
                    choices=[
                        ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'),
                        ('LOGIN', 'Login'), ('LOGOUT', 'Logout'),
                        ('PAYROLL_RUN', 'Payroll Run'), ('PAYROLL_APPROVE', 'Payroll Approve'),
                        ('PAYROLL_REJECT', 'Payroll Reject'), ('EXPORT', 'Data Export'),
                        ('PERMISSION_CHANGE', 'Permission Change'), ('WEBHOOK', 'Webhook Received'),
                    ],
                    db_index=True, max_length=32,
                )),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('integrity_seal', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('tenant', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='audit_logs',
                    to='tenants.tenant',
                )),
            ],
            options={
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
                'indexes': [
                    models.Index(fields=['tenant', 'timestamp'], name='audit_tenant_ts_idx'),
                    models.Index(fields=['actor_id', 'timestamp'], name='audit_actor_ts_idx'),
                    models.Index(fields=['resource_type', 'resource_id'], name='audit_resource_idx'),
                ],
            },
        ),
        # ── Install the PostgreSQL tamper-lock trigger ────────────────────────
        # only runs when connecting to PostgreSQL. Safe for SQLite local tests.
        migrations.RunPython(
            create_trigger,
            reverse_code=drop_trigger,
        ),
    ]
